# Generated by Django 4.2.23 on 2025-07-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name_plural': 'Inboxes'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
