# Generated by Django 4.2.23 on 2025-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(default='Bronze', max_length=10),
        ),
    ]
